###############################################################################
##                                                                           ##
## node.jsをインストールするに当たって必要な情報を記載する                           ## 
## Copyright Toru MITANI(mitani@daisuke2.com)                                ##
##                                                                           ##
###############################################################################

# node.js avi_api_version
nodejs_version: "14.15.0"

install_pakage:
  - "npm"