###############################################################################
##                                                                           ##
## rbenvをインストールするに当たって必要な情報を記載する                             ## 
## Copyright Toru MITANI(mitani@daisuke2.com)                                ##
##                                                                           ##
###############################################################################

# ruby avi_api_version
ruby_version: "2.7.2"

install_pakage:
  - "git"
  - "gcc"
  - "make"
  - "openssl-devel"
  - "readline-devel"
  - "zlib-devel"
  - "rsync"
  - "bzip2"
  - "gcc-c++"
  - "clang"
  - "postgresql-devel"

rbenv_repository: "https://github.com/sstephenson/rbenv.git"
rbenv_directory: ".rbenv"

env:
  - {path: 'export PATH=~/.rbenv/bin:\$PATH', guard: "rbenv"}
  - {path: '''eval "$(rbenv init -)"''', guard: "init"}

ruby_build_repository: "https://github.com/sstephenson/ruby-build.git"
ruby_build_path: ".rbenv/plugins/ruby-build"




