---

- name: Add repository
  yum_repository: 
    name: yarn
    description: Yarn Repository
    baseurl: "{{ repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ yarn_gpgkey_url }}"
    enabled: yes

# yarnのバージョン確認
- name:  yarn version
  debug:
    msg: "{{ yarn_version }}"

# packegeのインストール
- name: install yarn
  yum:
    name: "{{ install_pakage }}"
    state: present