###############################################################################
##                                                                           ##
## railsをインストールするに当たって必要な情報を記載する                             ## 
## Copyright Toru MITANI(mitani@daisuke2.com)                                ##
##                                                                           ##
###############################################################################

# Ruby On Rails version
rails_version: "6.0.3.4"